# Generated by Django 5.2.16 on 2026-07-14 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=160)),
                ("icon", models.CharField(default="🏅", max_length=8)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("score", "Puntaje"),
                            ("carrots", "Zanahorias"),
                            ("level", "Nivel"),
                            ("games", "Partidas"),
                            ("combo", "Combo"),
                        ],
                        max_length=12,
                    ),
                ),
                ("threshold", models.PositiveIntegerField()),
                (
                    "accessory_reward",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "Sin accesorio"),
                            ("scarf", "Pañuelo verde"),
                            ("flower", "Flor silvestre"),
                            ("bow", "Moño zanahoria"),
                            ("clover", "Trébol de la suerte"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "logro",
                "verbose_name_plural": "logros",
                "ordering": ["sort_order", "threshold"],
            },
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="bunny_accessory",
            field=models.CharField(
                choices=[
                    ("none", "Sin accesorio"),
                    ("scarf", "Pañuelo verde"),
                    ("flower", "Flor silvestre"),
                    ("bow", "Moño zanahoria"),
                    ("clover", "Trébol de la suerte"),
                ],
                default="none",
                max_length=16,
                verbose_name="accesorio",
            ),
        ),
        migrations.CreateModel(
            name="PlayerAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="core.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "logro desbloqueado",
                "verbose_name_plural": "logros desbloqueados",
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
