# Generated by Django 5.2.16 on 2026-07-14 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_achievement_playerprofile_bunny_accessory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamescore",
            name="max_combo",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(50)]
            ),
        ),
    ]
