# Generated by Django 5.2.16 on 2026-07-14 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_gamescore_max_combo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="gamescore",
            name="score_rank_idx",
        ),
        migrations.AddField(
            model_name="gamescore",
            name="mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("timed", "60 segundos"),
                    ("one_life", "Una sola vida"),
                    ("high_carrots", "Solo zanahorias altas"),
                    ("fast_forest", "Bosque veloz"),
                ],
                db_index=True,
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("timed", "60 segundos"),
                    ("one_life", "Una sola vida"),
                    ("high_carrots", "Solo zanahorias altas"),
                    ("fast_forest", "Bosque veloz"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="bunny_breed",
            field=models.CharField(
                choices=[
                    ("lop", "Belier"),
                    ("dwarf", "Enano neerlandés"),
                    ("angora", "Angora"),
                    ("rex", "Rex"),
                ],
                default="lop",
                max_length=16,
                verbose_name="raza",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="accessory_reward",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Sin accesorio"),
                    ("scarf", "Pañuelo verde"),
                    ("flower", "Flor silvestre"),
                    ("bow", "Moño zanahoria"),
                    ("clover", "Trébol de la suerte"),
                    ("cap", "Gorrito de explorador"),
                    ("collar", "Collarín de flores"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="bunny_accessory",
            field=models.CharField(
                choices=[
                    ("none", "Sin accesorio"),
                    ("scarf", "Pañuelo verde"),
                    ("flower", "Flor silvestre"),
                    ("bow", "Moño zanahoria"),
                    ("clover", "Trébol de la suerte"),
                    ("cap", "Gorrito de explorador"),
                    ("collar", "Collarín de flores"),
                ],
                default="none",
                max_length=16,
                verbose_name="accesorio",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="bunny_color",
            field=models.CharField(
                choices=[
                    ("snow", "Blanco nieve"),
                    ("cocoa", "Cacao"),
                    ("sand", "Arena"),
                    ("moon", "Gris luna"),
                    ("caramel", "Caramelo"),
                    ("patch", "Manchado"),
                ],
                default="snow",
                max_length=12,
                verbose_name="pelaje",
            ),
        ),
        migrations.AddIndex(
            model_name="gamescore",
            index=models.Index(
                fields=["mode", "-score", "created_at"], name="score_mode_rank_idx"
            ),
        ),
    ]
