# Generated by Django 5.2.16 on 2026-07-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_gamescore_score_rank_idx_gamescore_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamescore",
            name="mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("timed", "60 segundos"),
                    ("one_life", "Una sola vida"),
                    ("high_carrots", "Solo zanahorias altas"),
                    ("fast_forest", "Bosque veloz"),
                    ("light_grey", "Light grey"),
                ],
                db_index=True,
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("timed", "60 segundos"),
                    ("one_life", "Una sola vida"),
                    ("high_carrots", "Solo zanahorias altas"),
                    ("fast_forest", "Bosque veloz"),
                    ("light_grey", "Light grey"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
