# Generated by Codex on 2026-07-15

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


ACCESSORY_CHOICES = [
    ("none", "Sin accesorio"), ("scarf", "Pañuelo verde"), ("flower", "Flor silvestre"),
    ("bow", "Moño zanahoria"), ("clover", "Trébol de la suerte"), ("cap", "Gorrito de explorador"),
    ("collar", "Collarín de flores"), ("crown", "Corona de tréboles"), ("glasses", "Anteojos redondos"),
    ("backpack", "Mochila viajera"), ("star", "Estrella de sendero"), ("moon_pin", "Pin lunar"),
    ("rainbow", "Cinta arcoíris"),
]
MODES = [("normal", "Normal"), ("timed", "60 segundos"), ("one_life", "Una sola vida"), ("high_carrots", "Solo zanahorias altas"), ("fast_forest", "Bosque veloz")]


class Migration(migrations.Migration):

    dependencies = [("core", "0005_add_light_grey_mode"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.AddField("gamescore", "distance_m", models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)])),
        migrations.AddField("playerprofile", "coin_balance", models.PositiveIntegerField(default=0, verbose_name="monedas")),
        migrations.AddField("playerprofile", "preferred_theme", models.CharField(choices=[("white", "Blanco original"), ("light_grey", "Light grey")], default="white", max_length=20, verbose_name="tema")),
        migrations.AlterField("playerprofile", "bunny_accessory", models.CharField(choices=ACCESSORY_CHOICES, default="none", max_length=16, verbose_name="accesorio")),
        migrations.AlterField("achievement", "accessory_reward", models.CharField(blank=True, choices=ACCESSORY_CHOICES, default="", max_length=16)),
        migrations.AlterField("gamescore", "mode", models.CharField(choices=MODES, db_index=True, default="normal", max_length=20)),
        migrations.AlterField("gamesession", "mode", models.CharField(choices=MODES, default="normal", max_length=20)),
        migrations.CreateModel(
            name="AccessoryPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("accessory", models.CharField(choices=ACCESSORY_CHOICES, max_length=16)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accessory_purchases", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "accesorio comprado", "verbose_name_plural": "accesorios comprados", "ordering": ["-purchased_at"], "unique_together": {("user", "accessory")}},
        ),
    ]
