# Generated by Django 5.2.16 on 2026-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_shop_theme_and_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="bunny_accessory",
            field=models.CharField(
                default="none",
                help_text="Hasta 5 accesorios separados por comas.",
                max_length=100,
                verbose_name="accesorios",
            ),
        ),
    ]
